import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import ReactQueryProvider from "@/providers/ReactQueryProvider"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Sreyoshi Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {/* ⚡ NextAuth এর SessionProvider */}
        <SessionProvider>
          {/* ⚡ TanStack Query এর ReactQueryProvider */}
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}